Tests for notifications
Project-Stage-Academy/UA-1155-bravo pull request #103
Opened 2024-05-18 11:12 UTC by alona-ruda

2024-05-18 17:49 UTC, mehalyna requested changes

2024-05-18 17:49 UTC, mehalyna commented on ForumProject/notifications/tests.py
1. `self.client = APIClient()` and `self.client.credentials(HTTP_AUTHORIZATION='Bearer ' + self.tokens[...])` are repeated in each test method. Consider using a setup method to initialize the client once.
```
def setUp(self):
    self.client = APIClient()
    self.client.credentials(HTTP_AUTHORIZATION='Bearer ' + self.tokens[f'{self.actors[1]}@user.com'])
```
2. The URL names and expected statuses are hardcoded. If these endpoints change, it will require updating all occurrences. Consider using a config or constants file.
```
FOLLOW_URL = reverse('projects:follow', kwargs={'project_id': self.project.id})
UNFOLLOW_URL = reverse('projects:delist_project', kwargs={'project_id': self.project.id})
SUBSCRIPTION_URL = reverse('projects:subscription', kwargs={'project_id': self.project.id, 'share': 50})
```

2024-05-18 21:34 UTC, avu-ua approved these changes

2024-05-19 07:48 UTC, DariyBautista approved these changes

2024-05-19 09:17 UTC, alona-ruda commented on ForumProject/notifications/tests.py
I changed code according to your reviews

2024-05-19 12:41 UTC, mehalyna approved these changes

2024-05-20 09:44 UTC, merged