Project app refactored
Project-Stage-Academy/UA-1155-bravo pull request #106
Opened 2024-05-19 23:25 UTC by avu-ua

1. Added functionality of logs creation when a file is added for the Project or deleted, or when file description is changed.
2. Amended mechanism for triggering logs - now is arranged vie event listeners at signals.py rather hen in custom `create` / `update` / `destroy` method in viewsets. 
3. Amended logic for creation folders on the server to store files of the Project. Previously folders were named using startup-slugs and Project-slugs - so long as names of Startups and/or Projects can change that logic could lead to vulnerability of getting files lost on he server. Now the folders are named based on Primary Key of the Startups and Projects.

2024-05-20 06:21 UTC, mehalyna requested changes

2024-05-20 06:21 UTC, mehalyna commented on ForumProject/projects/signals.py
Add error handling for cases where the related objects (e.g., `UserRoleCompany`) might not exist. This prevents your signal handlers from crashing if the data is inconsistent.

2024-05-21 09:44 UTC, avu-ua commented on ForumProject/projects/signals.py
This has been done.

2024-05-21 09:53 UTC, alona-ruda approved these changes

2024-05-21 14:28 UTC, mehalyna approved these changes

2024-05-21 14:59 UTC, oleksandr-liashenko approved these changes

2024-05-21 16:17 UTC, merged