#82 testing messaging functionality
Project-Stage-Academy/UA-1155-bravo pull request #117
Opened 2024-05-23 11:09 UTC by Andrewakiv

2024-05-23 14:33 UTC, mehalyna requested changes

2024-05-23 14:33 UTC, mehalyna commented on ForumProject/communications/tests.py
> +                                              startup_address='I Franka 123')
Move static data creation to `setUpTestData` instead of `setUp` to reduce redundancy and improve test performance.

2024-05-23 14:33 UTC, mehalyna commented on ForumProject/communications/tests.py
> +        Room.objects.all().delete()
Ensure the `tearDown` method cleans up all necessary data. You might want to use Django's `TransactionTestCase` to automatically handle database rollbacks.

2024-05-23 14:33 UTC, mehalyna commented on ForumProject/communications/tests.py
> +        login = self.client.login(email='investor@example.com', password='password')
Check the return value of `self.client.login` to ensure the login was successful before proceeding with the test.
For lines 103, 108 as well

2024-05-23 20:49 UTC, Andrewakiv commented on ForumProject/communications/tests.py
> +        Room.objects.all().delete()
done

2024-05-23 20:50 UTC, Andrewakiv commented on ForumProject/communications/tests.py
> +        login = self.client.login(email='investor@example.com', password='password')
done

2024-05-23 20:50 UTC, Andrewakiv commented on ForumProject/communications/tests.py
> +                                              startup_address='I Franka 123')
done

2024-05-24 19:10 UTC, mehalyna approved these changes

2024-05-25 06:24 UTC, merged