#112 implement funding check for investor subscriptions
Project-Stage-Academy/UA-1155-bravo pull request #118
Opened 2024-05-23 12:11 UTC by alona-ruda

2024-05-23 12:41 UTC, DariyBautista approved these changes

2024-05-23 14:42 UTC, mehalyna requested changes

2024-05-23 14:42 UTC, mehalyna commented on ForumProject/projects/models.py
> +        return total_funding or 0
Add type hints for method parameters and return values.
Add basic error handling to manage potential issues gracefully.
_Example_
```
    def get_total_funding(cls, project_id: int) -> float:
        """
        Calculate the total funding from all investors for a specific project.
        
        Args:
            project_id (int): The ID of the project.
        
        Returns:
            float: The total amount of funding.
        """
        total_funding = cls.objects.filter(
            project_id=project_id
        ).aggregate(total=models.Sum('share'))['total']
        
        return float(total_funding or 0)
```

2024-05-24 11:57 UTC, alona-ruda commented on ForumProject/projects/models.py
> +        return total_funding or 0
Added

2024-05-24 19:11 UTC, mehalyna approved these changes

2024-05-25 09:16 UTC, merged