#2 starter django project
Project-Stage-Academy/UA-1155-bravo pull request #27
Opened 2024-04-18 09:25 UTC by DariyBautista

Created Starter Django Project:

Сreated an empty django project "ForumProject".

requirements.txt - a starting set of libraries
configured the settings.py file - Information about DB is individual for each one, stored in the .env file.
basic URL route - the default welcome page opens

2024-04-18 09:54 UTC, mehalyna requested changes

2024-04-18 09:54 UTC, mehalyna commented on ForumProject/ForumProject/settings.py
Please, add logging configurations to help with debugging and to capture errors in production. For example:
```
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'ERROR',
        },
    },
}
```

2024-04-18 09:54 UTC, mehalyna commented on ForumProject/ForumProject/urls.py
> +    return HttpResponse("Hello, team!")
Consider enhancing the response from your `home` view to include more complex HTML or integrate a template. This practice helps you prepare for more complex view development
```
def home(request):
    context = {'message': "Hello, team!"}
    return render(request, 'home.html', context)
```

2024-04-18 15:34 UTC, mehalyna approved these changes

2024-04-19 14:24 UTC, avu-ua approved these changes

2024-04-19 18:07 UTC, merged