#64 Testing startups: Post, Delete, Put (  sub-task  #13)
Project-Stage-Academy/UA-1155-bravo pull request #68
Opened 2024-05-01 18:41 UTC by DariyBautista

Tests for creating, editing, deleting (checking for open projects), data validation, filtering and searching startups

2024-05-02 17:43 UTC, mehalyna approved these changes

2024-05-02 17:43 UTC, mehalyna commented on ForumProject/startups/tests.py
Consider adding tests that cover more edge cases, such as attempting to update or delete startups that do not exist or providing invalid data formats

2024-05-02 17:43 UTC, mehalyna commented on ForumProject/startups/tests.py
> +        self.assertEqual(Startup.objects.count(), 1)
Consider also checking the content of the response for POST, PUT, and GET requests to ensure that the API returns the expected data. This can help catch serialization and permission issues.
E.g.
```
def test_create_startup(self):
    response = self.client.post(self.startup_add_url, self.startup_data, format='json')
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
    self.assertEqual(Startup.objects.count(), 1)
    self.assertEqual(response.data['startup_name'], 'Django Dribblers') 

```

2024-05-02 17:43 UTC, mehalyna commented on ForumProject/startups/views.py
> +        return Startup.objects.filter(userstartup__customuser=user_id)
If the list of startups can grow significantly, consider implementing pagination to manage the data volume efficiently

2024-05-02 17:45 UTC, mehalyna requested changes

2024-05-02 17:45 UTC, mehalyna commented on ForumProject/startups/views.py
> +        return Startup.objects.filter(userstartup__customuser=user_id)
_Note_

2024-05-02 18:48 UTC, DariyBautista commented on ForumProject/startups/views.py
> +        return Startup.objects.filter(userstartup__customuser=user_id)
Done, thanks!

2024-05-02 18:48 UTC, DariyBautista commented on ForumProject/startups/views.py
> +        return Startup.objects.filter(userstartup__customuser=user_id)
Done, thanks!

2024-05-02 18:48 UTC, DariyBautista commented on ForumProject/startups/tests.py
> +        self.assertEqual(Startup.objects.count(), 1)
Many were already done, I added more where needed, thanks!

2024-05-02 18:48 UTC, DariyBautista commented on ForumProject/startups/tests.py
Added, thanks!

2024-05-03 06:55 UTC, mehalyna approved these changes

2024-05-03 13:29 UTC, merged