#66 api endpoints for managing email notification preferences
Project-Stage-Academy/UA-1155-bravo pull request #90
Opened 2024-05-09 12:18 UTC by alona-ruda

2024-05-09 14:26 UTC, mehalyna requested changes

2024-05-09 14:26 UTC, mehalyna commented on ForumProject/notifications/serializers.py
> +        fields = ['project', 'startup_name', 'investor', 'trigger', 'initiator', 'datetime']
Define each field explicitly in the serializer to control serialization behavior and add help text or validation as necessary.
```
from rest_framework import serializers
from .models import Notification

class NotificationSerializer(serializers.ModelSerializer):
    project = serializers.PrimaryKeyRelatedField(read_only=True)
    startup_name = serializers.CharField()
    investor = serializers.PrimaryKeyRelatedField(read_only=True)
    trigger = serializers.ChoiceField(choices=Notification.TRIGGER_CHOICES)
    initiator = serializers.ChoiceField(choices=Notification.INITIATOR_CHOICES)
    date_time = serializers.DateTimeField(source='datetime')

    class Meta:
        model = Notification
        fields = ['project', 'startup_name', 'investor', 'trigger', 'initiator', 'date_time']
```

2024-05-09 14:26 UTC, mehalyna commented on ForumProject/notifications/serializers.py
Add custom validation methods to ensure the integrity of data, especially for fields with specific business logic
_Example validation for trigger:_
```
def validate_trigger(self, value):
    if value not in [choice[0] for choice in Notification.TRIGGER_CHOICES]:
        raise serializers.ValidationError("This is not a valid trigger.")
    return value
```

2024-05-09 14:26 UTC, mehalyna commented on ForumProject/notifications/views.py
> +        return Notification.objects.get_or_create(user=self.request.user)[0]
The method does not handle potential exceptions that could arise if the 'Notification' model does not include a user field or if the database query fails for some reason. Pls, refine the `get_object` method to handle cases where the `Notification` object cannot be found or created due to incorrect model configurations or database issues.
```
from django.http import Http404

def get_object(self):
    obj, created = Notification.objects.get_or_create(user=self.request.user)
    if obj is None:
        raise Http404("Notification object is not available or failed to create.")
    return obj
```

2024-05-09 14:26 UTC, mehalyna commented on ForumProject/notifications/views.py
**SRP** The view handles both retrieving and creating a notification object which might complicate the view's responsibility. This could be separated for clarity and to adhere to the single responsibility principle.
_Examples_
1) RetrieveUpdateAPIView for Existing Notifications
```
class NotificationRetrieveUpdateAPIView(generics.RetrieveUpdateAPIView):
    serializer_class = NotificationSerializer
    permission_classes = [IsAuthenticated]

    def get_object(self):
        obj, _ = Notification.objects.get_or_create(user=self.request.user)
        return obj
```
2) CreateAPIView for Creating New Notifications
```
class NotificationCreateAPIView(generics.CreateAPIView):
    serializer_class = NotificationSerializer
    permission_classes = [IsAuthenticated]

    def perform_create(self, serializer):
        # Ensure the notification is associated with the current user
        serializer.save(user=self.request.user)
```
URL Configuration
```
from django.urls import path
from .views import NotificationRetrieveUpdateAPIView, NotificationCreateAPIView

urlpatterns = [
    path('api/notifications/', NotificationCreateAPIView.as_view(), name='create_notification'),
    path('api/notifications/<int:pk>/', NotificationRetrieveUpdateAPIView.as_view(), name='retrieve_update_notification'),
]
```

2024-05-09 14:26 UTC, mehalyna commented on ForumProject/users/utils.py
> +            send_email = True
The method might be more efficient if refactored to reduce duplication:
```
events = {
    'new_follow': prefs.new_follows,
    'new_message': prefs.new_messages,
    'project_update': prefs.project_updates
}
send_email = events.get(event_type, False)
```

2024-05-09 14:26 UTC, mehalyna commented on ForumProject/users/utils.py
> +                body='Hi! ' + user.first_name + event_type,
```
body=f"Hi {user.first_name},\n\nYou have a new {event_type}!"
```

2024-05-13 13:31 UTC, alona-ruda commented
merged #66 into #63-66-88

2024-05-13 13:32 UTC, alona-ruda commented
merged #66 into #63-66-88

2024-05-13 13:33 UTC, alona-ruda commented
merged #66 into #63-66-88-revisited

2024-05-13 13:33 UTC, closed without merging