#78 develop messaging api endpoints 19 3]
Project-Stage-Academy/UA-1155-bravo pull request #96
Opened 2024-05-12 21:00 UTC by DmAlexx

2024-05-16 06:01 UTC, mehalyna requested changes

2024-05-16 06:01 UTC, mehalyna commented on ForumProject/communications/consumers.py
> +        self.room = Room.objects.get(name=self.room_name)
The `Room.objects.get(name=self.room_name)` call  could raise a `Room.DoesNotExist` exception if the room does not exist. It's better to handle this case explicitly to prevent the WebSocket connection from being accepted if the room does not exist, which could lead to errors down the line.

2024-05-16 06:01 UTC, mehalyna commented on ForumProject/communications/consumers.py
1) You are checking if `self.user.is_authenticated` multiple times. It would be cleaner and more efficient to handle this once at the beginning of the `connect` method and `disconnect` or prevent further execution if the user is not authenticated.
2) When broadcasting messages, there's currently no filtering to ensure that a user can only send messages if they are a participant in the room. This could potentially allow a user to send messages to a room they are not part of if they can guess or know the room's name.
3) You add the user to the room group and potentially other groups without ensuring that the connect is actually successful from a business logic perspective (e.g., the room exists, and the user is allowed in the room). Ensure all checks are passed before adding the user to groups.

2024-05-16 06:01 UTC, mehalyna commented on ForumProject/communications/consumers.py
> +        Message.objects.create(user=self.user, room=self.room, content=message)
The `Message.objects.create`  does not handle any exceptions that could occur during database operations. Consider adding exception handling around this to manage issues like database write failures gracefully.

2024-05-16 06:01 UTC, mehalyna commented on ForumProject/communications/models.py
> +        }
These methods assume a specific format for the room's name field that includes two user IDs separated by underscores. This is prone to errors if the format is not strictly followed. Consider adding error handling to manage cases where the name does not contain the expected number of underscores or user IDs.

2024-05-16 06:01 UTC, mehalyna commented on ForumProject/communications/models.py
> +            'user_2': User.objects.get(id=self.get_users_id()['user_2']).first_name
The `User.objects.get()` call can raise a `User.DoesNotExist` exception if no user with the provided ID exists. Handling this case gracefully would improve the robustness of the method.

2024-05-16 06:01 UTC, mehalyna commented on ForumProject/communications/static/room.js
> +        chatMessageSend.click();
The usage of `e.keyCode` is deprecated. Consider using `e.key` instead for detecting the enter key press:
```
chatMessageInput.onkeyup = function(e) {
    if (e.key === "Enter") {
        chatMessageSend.click();
    }
};
```

2024-05-16 06:01 UTC, mehalyna commented on ForumProject/communications/views.py
1) Error handling is minimal. Consider adding more robust error handling and user feedback mechanisms.
2) Adding explicit permission classes to views handling sensitive data like messages and conversations is strongly advised to protect user data.
3) Consider adding more detailed docstrings to each view to explain the purpose, expected parameters, and return types, which can be beneficial for maintenance and future development.

2024-05-23 14:12 UTC, mehalyna approved these changes

2024-05-23 20:01 UTC, Andrewakiv approved these changes

2024-05-23 21:17 UTC, merged